const MENSAJES = {
    AUTOR: {
        LISTAR_ERROR: 'ERROR AL LISTAR AUTORES',
        INSERTAR_ERROR: 'ERROR AL INSERTAR EL AUTOR',
        ACTUALIZAR_ERROR: 'ERROR AL ACTUALIZAR EL AUTOR',
        ELIMINAR_ERROR: 'ERROR AL ELIMINAR EL AUTOR',
        VALIDACION: 'TODOS LOS CAMPOS SON OBLIGATORIOS'
    },
    EDITORIAL: {
        LISTAR_ERROR: 'ERROR AL LISTAR EDITORIALES',
        INSERTAR_ERROR: 'ERROR AL INSERTAR EDITORIAL',
        ACTUALIZAR_ERROR: 'ERROR AL ACTUALIZAR EDITORIAL',
        ELIMINAR_ERROR: 'ERROR AL ELIMINAR EDITORIAL',
        VALIDACION: 'TODOS LOS CAMPOS SON OBLIGATORIOS'
    },
    GENERAL: {
        ERROR_SERVIDOR: 'ERROR INTERNO DEL SERVIDOR',
        NOT_FOUND: 'RECURSO NO ENCONTRADO',
        SUCCESS: 'OPERACION REALIZADA CORRECTAMENTE'
    },
    USUARIO: {
        INSERTAR_ERROR: 'ERROR AL REGISTRAR USUARIO',
        VALIDACION: 'TODOS LOS CAMPOS SON OBLIGATORIOS'
    },
    LIBRO: {
        LISTAR_ERROR: 'ERROR AL LISTAR LIBROS',
        INSERTAR_ERROR: 'ERROR AL INSERTAR LIBRO',
        ACTUALIZAR_ERROR: 'ERROR AL ACTUALIZAR LIBRO',
        ELIMINAR_ERROR: 'ERROR AL ELIMINAR LIBRO',
        VALIDACION: 'TODOS LOS CAMPOS SON OBLIGATORIOS'
    }
};

module.exports = MENSAJES;
